# Generated by Django 4.2.13 on 2024-05-24 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange_rates.currency'),
        ),
        migrations.DeleteModel(
            name='CurrencyRate',
        ),
    ]
